### ISSUE TITLE
Usage Reporting "Request" Class Missing?

### ISSUE THREAD

**Issue by blm-unikent** [lucisgit/php-panopto-api#1]
We are getting folder and user lists very happily using the respective request and response classes, but usage reporting doesn't have a request class, just a response class.

Are there examples of how to do usage reporting?  Or do we need to create the develop a respective request class first?

**Comment by kabalin** [comment]
Hello! Pleased to see someone using this library! What exactly are you trying to achieve?

All required classes are in place. I do not have usage reporting example in the code, but following the [example class](https://github.com/lucisgit/php-panopto-api/blob/master/examples/samplelib.php), you need to define `$this->urclient = $panoptoclient->UsageReporting();` in the constructor first. Then, to query user stats (say by calling `UsageReporting.GetUserDetailedUsage` method), your method may look like:
```
        $username = 'somegooduser';
        try {
            $param = new \Panopto\UserManagement\GetUserByKey($this->auth, $username);
            $user = $this->umclient->GetUserByKey($param)->getGetUserByKeyResult();

            $pagination = new \Panopto\RemoteRecorderManagement\Pagination();
            $pagination->setPageNumber(1);
            $pagination->setMaxNumberResults(100);

            $param = new \Panopto\UsageReporting\GetUserDetailedUsage($this->auth, $user->getUserId(), $pagination);
            $usage = $this->urclient->GetUserDetailedUsage($param)->getGetUserDetailedUsageResult()->getPagedResponses();
            foreach ($usage as $usageitem) {
                $detailedusage = $usageitem->getDetailedUsageResponseItem();
                echo "session: " . $detailedusage->getSessionId() . " viewed " . $detailedusage->getSecondsViewed() . "(sec.)\n";
            }
        } catch(Exception $e) {
            throw new SoapFault('client', $e->getMessage());
        }
```

**Comment by blm-unikent** [comment]
Thanks that works
